# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: locations.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='locations.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0flocations.proto\x1a\x1cgoogle/api/annotations.proto\"\x12\n\x10LocationsRequest\"R\n\x08Location\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x10\n\x08subtitle\x18\x03 \x01(\t\x12\x0b\n\x03lat\x18\x04 \x01(\x02\x12\x0c\n\x04long\x18\x05 \x01(\x02\"1\n\x11LocationsResponse\x12\x1c\n\tlocations\x18\x01 \x03(\x0b\x32\t.Location\"+\n\x15LocationDetailRequest\x12\x12\n\nlocationId\x18\x01 \x01(\x05\"\xa3\x01\n\x16LocationDetailResponse\x12\x1b\n\x08location\x18\x01 \x01(\x0b\x32\t.Location\x12\x30\n\x07\x63omment\x18\x02 \x03(\x0b\x32\x1f.LocationDetailResponse.Comment\x1a:\n\x07\x43omment\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08imageUrl\x18\x03 \x01(\t2\xc5\x01\n\tLocations\x12M\n\x10RequestLocations\x12\x11.LocationsRequest\x1a\x12.LocationsResponse\"\x12\x82\xd3\xe4\x93\x02\x0c\x12\n/locations\x12i\n\x15RequestLocationDetail\x12\x16.LocationDetailRequest\x1a\x17.LocationDetailResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/locations/{locationId}b\x06proto3')
  ,
  dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,])




_LOCATIONSREQUEST = _descriptor.Descriptor(
  name='LocationsRequest',
  full_name='LocationsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=67,
)


_LOCATION = _descriptor.Descriptor(
  name='Location',
  full_name='Location',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Location.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='title', full_name='Location.title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='subtitle', full_name='Location.subtitle', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lat', full_name='Location.lat', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='long', full_name='Location.long', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=151,
)


_LOCATIONSRESPONSE = _descriptor.Descriptor(
  name='LocationsResponse',
  full_name='LocationsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='locations', full_name='LocationsResponse.locations', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=153,
  serialized_end=202,
)


_LOCATIONDETAILREQUEST = _descriptor.Descriptor(
  name='LocationDetailRequest',
  full_name='LocationDetailRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='locationId', full_name='LocationDetailRequest.locationId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=204,
  serialized_end=247,
)


_LOCATIONDETAILRESPONSE_COMMENT = _descriptor.Descriptor(
  name='Comment',
  full_name='LocationDetailResponse.Comment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='content', full_name='LocationDetailResponse.Comment.content', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='LocationDetailResponse.Comment.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='imageUrl', full_name='LocationDetailResponse.Comment.imageUrl', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=355,
  serialized_end=413,
)

_LOCATIONDETAILRESPONSE = _descriptor.Descriptor(
  name='LocationDetailResponse',
  full_name='LocationDetailResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='location', full_name='LocationDetailResponse.location', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='comment', full_name='LocationDetailResponse.comment', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_LOCATIONDETAILRESPONSE_COMMENT, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=250,
  serialized_end=413,
)

_LOCATIONSRESPONSE.fields_by_name['locations'].message_type = _LOCATION
_LOCATIONDETAILRESPONSE_COMMENT.containing_type = _LOCATIONDETAILRESPONSE
_LOCATIONDETAILRESPONSE.fields_by_name['location'].message_type = _LOCATION
_LOCATIONDETAILRESPONSE.fields_by_name['comment'].message_type = _LOCATIONDETAILRESPONSE_COMMENT
DESCRIPTOR.message_types_by_name['LocationsRequest'] = _LOCATIONSREQUEST
DESCRIPTOR.message_types_by_name['Location'] = _LOCATION
DESCRIPTOR.message_types_by_name['LocationsResponse'] = _LOCATIONSRESPONSE
DESCRIPTOR.message_types_by_name['LocationDetailRequest'] = _LOCATIONDETAILREQUEST
DESCRIPTOR.message_types_by_name['LocationDetailResponse'] = _LOCATIONDETAILRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LocationsRequest = _reflection.GeneratedProtocolMessageType('LocationsRequest', (_message.Message,), dict(
  DESCRIPTOR = _LOCATIONSREQUEST,
  __module__ = 'locations_pb2'
  # @@protoc_insertion_point(class_scope:LocationsRequest)
  ))
_sym_db.RegisterMessage(LocationsRequest)

Location = _reflection.GeneratedProtocolMessageType('Location', (_message.Message,), dict(
  DESCRIPTOR = _LOCATION,
  __module__ = 'locations_pb2'
  # @@protoc_insertion_point(class_scope:Location)
  ))
_sym_db.RegisterMessage(Location)

LocationsResponse = _reflection.GeneratedProtocolMessageType('LocationsResponse', (_message.Message,), dict(
  DESCRIPTOR = _LOCATIONSRESPONSE,
  __module__ = 'locations_pb2'
  # @@protoc_insertion_point(class_scope:LocationsResponse)
  ))
_sym_db.RegisterMessage(LocationsResponse)

LocationDetailRequest = _reflection.GeneratedProtocolMessageType('LocationDetailRequest', (_message.Message,), dict(
  DESCRIPTOR = _LOCATIONDETAILREQUEST,
  __module__ = 'locations_pb2'
  # @@protoc_insertion_point(class_scope:LocationDetailRequest)
  ))
_sym_db.RegisterMessage(LocationDetailRequest)

LocationDetailResponse = _reflection.GeneratedProtocolMessageType('LocationDetailResponse', (_message.Message,), dict(

  Comment = _reflection.GeneratedProtocolMessageType('Comment', (_message.Message,), dict(
    DESCRIPTOR = _LOCATIONDETAILRESPONSE_COMMENT,
    __module__ = 'locations_pb2'
    # @@protoc_insertion_point(class_scope:LocationDetailResponse.Comment)
    ))
  ,
  DESCRIPTOR = _LOCATIONDETAILRESPONSE,
  __module__ = 'locations_pb2'
  # @@protoc_insertion_point(class_scope:LocationDetailResponse)
  ))
_sym_db.RegisterMessage(LocationDetailResponse)
_sym_db.RegisterMessage(LocationDetailResponse.Comment)



_LOCATIONS = _descriptor.ServiceDescriptor(
  name='Locations',
  full_name='Locations',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=416,
  serialized_end=613,
  methods=[
  _descriptor.MethodDescriptor(
    name='RequestLocations',
    full_name='Locations.RequestLocations',
    index=0,
    containing_service=None,
    input_type=_LOCATIONSREQUEST,
    output_type=_LOCATIONSRESPONSE,
    options=_descriptor._ParseOptions(descriptor_pb2.MethodOptions(), _b('\202\323\344\223\002\014\022\n/locations')),
  ),
  _descriptor.MethodDescriptor(
    name='RequestLocationDetail',
    full_name='Locations.RequestLocationDetail',
    index=1,
    containing_service=None,
    input_type=_LOCATIONDETAILREQUEST,
    output_type=_LOCATIONDETAILRESPONSE,
    options=_descriptor._ParseOptions(descriptor_pb2.MethodOptions(), _b('\202\323\344\223\002\031\022\027/locations/{locationId}')),
  ),
])
_sym_db.RegisterServiceDescriptor(_LOCATIONS)

DESCRIPTOR.services_by_name['Locations'] = _LOCATIONS

# @@protoc_insertion_point(module_scope)
