# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import comments_pb2 as comments__pb2


class CommentsStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.RequestComments = channel.unary_unary(
        '/Comments/RequestComments',
        request_serializer=comments__pb2.CommentsRequest.SerializeToString,
        response_deserializer=comments__pb2.CommentsResponse.FromString,
        )


class CommentsServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def RequestComments(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CommentsServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'RequestComments': grpc.unary_unary_rpc_method_handler(
          servicer.RequestComments,
          request_deserializer=comments__pb2.CommentsRequest.FromString,
          response_serializer=comments__pb2.CommentsResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Comments', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
