# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: comments.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='comments.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0e\x63omments.proto\"$\n\x0f\x43ommentsRequest\x12\x11\n\tcontentId\x18\x01 \x01(\x05\"{\n\x10\x43ommentsResponse\x12+\n\x08\x63omments\x18\x01 \x03(\x0b\x32\x19.CommentsResponse.Comment\x1a:\n\x07\x43omment\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08imageUrl\x18\x03 \x01(\t2D\n\x08\x43omments\x12\x38\n\x0fRequestComments\x12\x10.CommentsRequest\x1a\x11.CommentsResponse\"\x00\x62\x06proto3')
)




_COMMENTSREQUEST = _descriptor.Descriptor(
  name='CommentsRequest',
  full_name='CommentsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='contentId', full_name='CommentsRequest.contentId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=54,
)


_COMMENTSRESPONSE_COMMENT = _descriptor.Descriptor(
  name='Comment',
  full_name='CommentsResponse.Comment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='content', full_name='CommentsResponse.Comment.content', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='CommentsResponse.Comment.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='imageUrl', full_name='CommentsResponse.Comment.imageUrl', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=179,
)

_COMMENTSRESPONSE = _descriptor.Descriptor(
  name='CommentsResponse',
  full_name='CommentsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='comments', full_name='CommentsResponse.comments', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_COMMENTSRESPONSE_COMMENT, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=179,
)

_COMMENTSRESPONSE_COMMENT.containing_type = _COMMENTSRESPONSE
_COMMENTSRESPONSE.fields_by_name['comments'].message_type = _COMMENTSRESPONSE_COMMENT
DESCRIPTOR.message_types_by_name['CommentsRequest'] = _COMMENTSREQUEST
DESCRIPTOR.message_types_by_name['CommentsResponse'] = _COMMENTSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CommentsRequest = _reflection.GeneratedProtocolMessageType('CommentsRequest', (_message.Message,), dict(
  DESCRIPTOR = _COMMENTSREQUEST,
  __module__ = 'comments_pb2'
  # @@protoc_insertion_point(class_scope:CommentsRequest)
  ))
_sym_db.RegisterMessage(CommentsRequest)

CommentsResponse = _reflection.GeneratedProtocolMessageType('CommentsResponse', (_message.Message,), dict(

  Comment = _reflection.GeneratedProtocolMessageType('Comment', (_message.Message,), dict(
    DESCRIPTOR = _COMMENTSRESPONSE_COMMENT,
    __module__ = 'comments_pb2'
    # @@protoc_insertion_point(class_scope:CommentsResponse.Comment)
    ))
  ,
  DESCRIPTOR = _COMMENTSRESPONSE,
  __module__ = 'comments_pb2'
  # @@protoc_insertion_point(class_scope:CommentsResponse)
  ))
_sym_db.RegisterMessage(CommentsResponse)
_sym_db.RegisterMessage(CommentsResponse.Comment)



_COMMENTS = _descriptor.ServiceDescriptor(
  name='Comments',
  full_name='Comments',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=181,
  serialized_end=249,
  methods=[
  _descriptor.MethodDescriptor(
    name='RequestComments',
    full_name='Comments.RequestComments',
    index=0,
    containing_service=None,
    input_type=_COMMENTSREQUEST,
    output_type=_COMMENTSRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_COMMENTS)

DESCRIPTOR.services_by_name['Comments'] = _COMMENTS

# @@protoc_insertion_point(module_scope)
