# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import locations_pb2 as locations__pb2


class LocationsStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.RequestLocations = channel.unary_unary(
        '/Locations/RequestLocations',
        request_serializer=locations__pb2.LocationsRequest.SerializeToString,
        response_deserializer=locations__pb2.LocationsResponse.FromString,
        )
    self.RequestLocationDetail = channel.unary_unary(
        '/Locations/RequestLocationDetail',
        request_serializer=locations__pb2.LocationDetailRequest.SerializeToString,
        response_deserializer=locations__pb2.LocationDetailResponse.FromString,
        )


class LocationsServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def RequestLocations(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RequestLocationDetail(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_LocationsServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'RequestLocations': grpc.unary_unary_rpc_method_handler(
          servicer.RequestLocations,
          request_deserializer=locations__pb2.LocationsRequest.FromString,
          response_serializer=locations__pb2.LocationsResponse.SerializeToString,
      ),
      'RequestLocationDetail': grpc.unary_unary_rpc_method_handler(
          servicer.RequestLocationDetail,
          request_deserializer=locations__pb2.LocationDetailRequest.FromString,
          response_serializer=locations__pb2.LocationDetailResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Locations', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
